<?php

namespace BiblioBundle\Repository;

/**
 * AccesoireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccesoireRepository extends \Doctrine\ORM\EntityRepository
{
}
