<?php

namespace BiblioBundle\Repository;

/**
 * ListeCommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListeCommandeRepository extends \Doctrine\ORM\EntityRepository
{
}
