# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
         BiblioBundle\Entity\User:
             algorithm: bcrypt
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~

        in_database:
            entity:
                class: BiblioBundle:User
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: true
            provider : in_database
            form_login:
                login_path: login
                check_path: login
            logout:
                path: logout
                target: simpleuser
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/espace_bib, roles: ROLE_ADMIN }
    access_denied_url: /eror